image: python:3.7

stages:
  - build
  - test

cache:
  paths:
  - ~/.cache/pip/


build:
  stage: build

  variables:
    GIT_STRATEGY: none
  script:
  - apt-get update
  - mkdir -p media
  - pip install --upgrade pip
  - pip install -r requirements/base.txt
  - python manage.py collectstatic --noinput


