stages:
  - build
  - deploy

cache:
  paths:
  - ~/.cache/pip/

build:
  image: python:3.7
  stage: build
  script:
    - echo "Building Project"
    - /usr/bin/sudo apt-get update
    - pip install --upgrade pip
    - pip install -r requirements.txt


production:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deploying"
    - mkdir -p media
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py runserver 0.0.0.0:8000
  artifacts:
    paths:
        - log1/

