stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - pwd
    - git stash

  only:
    refs:
      - master
  script:
      - git checkout master
      - git pull origin master
      - sudo cp -R . /home/ubuntu/log1
      - cd /home/ubuntu
      - source env/bin/activate
      - cd /home/ubuntu/log1
      - sudo chmod -R a+rwx /home/ubuntu/log1
      - sudo chmod a+rwx /home/ubuntu/log1/logs/address.log
      - sudo chmod a+rwx /home/ubuntu/log1/logs/error.log
      - sudo chmod -R a+rwx /home/ubuntu/
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python manage.py makemigrations
      - python manage.py migrate
  artifacts:
    expire_in: 1 hour
    paths:
      - build
test:
  stage: test
  only:
    refs:
      - master
  script:
    - echo "Running log1 test suite......"
    - cd /home/ubuntu
    - source env/bin/activate
    - cd /home/ubuntu/log1
    - sudo chmod -R a+rwx /home/ubuntu/log1/media/
#    - python manage.py test

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - echo "Deploying to Log1 Server"
    - cd /home/ubuntu/log1
    - sudo systemctl restart gunicorn
