# Generated by Django 3.1.14 on 2023-08-17 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20230510_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('payment_term', models.FloatField(blank=True, null=True, verbose_name='payment_term')),
                ('payment_term_type', models.CharField(choices=[('on_net_pay', 'On Net Pay'), ('on_gross_pay', 'On Gross Pay'), ('100%_to_company', '100% To Company'), ('100%_to_consultant', '100% To Consultant')], max_length=30, verbose_name='payment_term_type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_payment', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_payment_term', to='project.project', verbose_name='project')),
            ],
        ),
    ]
