# Generated by Django 3.1.14 on 2023-08-17 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_projectpaymentterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpaymentterm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_payment', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
